Install HTSeq to make ngi_visualizations work
SciLifeLab/NGI-smRNAseq pull request #18
Opened 2017-05-31 14:34 UTC by chuan-wang

2017-05-31 14:50 UTC, ewels requested changes

2017-05-31 14:50 UTC, ewels commented on Dockerfile
>  ENV pip install --upgrade git+https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git
I just noticed that this is broken - should be `RUN` instead of `ENV`.

2017-05-31 14:50 UTC, ewels commented on Dockerfile
> +RUN curl -fsSL https://pypi.python.org/packages/46/f7/6105848893b1d280692eac4f4f3c08ed7f424cec636aeda66b50bbcf217e/HTSeq-0.7.2.tar.gz -o /opt/HTSeq-0.7.2.tar.gz && \
This is great, but if HTSeq is on PyPI then why not just install directly with `pip`? Just had a quick go locally and this seems to work:

```bash
RUN pip install numpy && pip install htseq
```

2017-05-31 14:51 UTC, ewels commented on Dockerfile
>  ENV pip install --upgrade git+https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git
Also it probably shouldn't have a space at the start of the line.. :)

2017-06-01 06:55 UTC, chuan-wang commented on Dockerfile
> +RUN curl -fsSL https://pypi.python.org/packages/46/f7/6105848893b1d280692eac4f4f3c08ed7f424cec636aeda66b50bbcf217e/HTSeq-0.7.2.tar.gz -o /opt/HTSeq-0.7.2.tar.gz && \
Thanks! I googled htseq and didn't find such a nice method for installation.

2017-06-01 06:55 UTC, chuan-wang commented on Dockerfile
>  ENV pip install --upgrade git+https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git
Also fixed.

2017-06-01 08:05 UTC, ewels commented on Dockerfile
> +RUN curl -fsSL https://pypi.python.org/packages/46/f7/6105848893b1d280692eac4f4f3c08ed7f424cec636aeda66b50bbcf217e/HTSeq-0.7.2.tar.gz -o /opt/HTSeq-0.7.2.tar.gz && \
No, their docs are not very clear. But the download address is PyPI (Python Package Index) and any package there should be installable with `pip`. It _should_ automatically install `numpy` as a dependency, but for whatever reason when I tested it the `htseq` installation instead just complained that `numpy` wasn't installed. The sequential installation seems to do the job though..

2017-06-01 08:05 UTC, ewels approved these changes

2017-06-01 08:05 UTC, merged